version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p $CIRCLE_TEST_REPORTS/testim/
      - run: testim --project "0ls1qMzNtbejgrNVKeoR" --grid "Testim-Grid" --token "PBaOXElGb3LYpRRDpDttL8g4EclvdVrwaNGs1btzeGOrxokBdo"
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results