name: Testim E2E
on:
    push:
        branches: [master]

jobs:
    secrets-in-github-actions:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16.13.0'
            - run: npm install -g @testim/testim-cli
            - run: testim --token ${{secrets.TESTIM_TOKEN}} --project ${{secrets.TESTIM_PROJECT_ID}} --grid ${{secrets.TESTIM_GRID}}
